repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff (formatter)
        entry: uvx ruff format
        args: ["--line-length=120", "--quiet"]
        language: system
        types: [python]
        require_serial: true

      - id: ruff-isort
        name: ruff (isort)
        entry: uvx ruff check --select I --fix
        language: system
        types: [python]
        require_serial: true

  - repo: https://github.com/pycqa/pylint
    rev: v3.3.4
    hooks:
      - id: pylint
        name: pylint (local env)
        entry: pylint
        language: system
        types: [python]
        files: \.py$
        args: [
          "--rcfile=.pylintrc",
          "--score=yes",
          "--disable=import-error"
        ]
        require_serial: true

  - repo: local
    hooks:
      - id: powershell-formatter
        name: PowerShell Formatter
        entry: pwsh ./tools/Format-Script.ps1
        language: system
        types: [powershell]
        files: \.ps1$
        args: []
        require_serial: true
        verbose: true

      - id: prettier
        name: Prettier (local)
        entry: npx prettier --write
        language: system
        types: [javascript, markdown, json, yaml]
        files: \.(js|md|json|ya?ml)$
        args: [--log-level=warn]
        require_serial: true

      - id: shfmt
        name: shfmt (local)
        entry: shfmt
        language: system
        types: [shell]
        files: \.sh$
        args: ["-i", "2", "-w"]
        require_serial: true
        verbose: true

      - id: clang-format
        name: clang-format (LLVM style)
        entry: clang-format
        language: system
        types: [c]
        files: \.(c|h)$
        args: ["-i", "-style=LLVM"]
        require_serial: true
        verbose: true