name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install uv and create venv
        run: |
          python -m pip install uv
          uv venv

      - name: Install dependencies
        run: |
          uv sync

      - name: Analysing the code with pylint
        run: |
          uv run pylint \
            --max-line-length=120 \
            --ignore=.venv \
            --disable=missing-module-docstring,missing-class-docstring,missing-function-docstring \
            --fail-under=9 \
            $(git ls-files '*.py')